#!/usr/bin/env -S podman-compose -f

services:
  yandex-disk:
#    build:
#      context: yandex-disk
#      args:
#        FEDORA_VERSION: 40
    image: docker.io/kran0/yandex-disk:latest
    restart: always
    environment:
      - HOME=${_CONTAINER_HOME:-/yandex-home}
    volumes:
      - yandex-home:${_CONTAINER_HOME:-/yandex-home}
      - ${YANDEX_SHARE}:${_CONTAINER_SHARE:-/yandex-share}
    command: [ "--no-daemon", "start",
               "--dir=${_CONTAINER_SHARE:-/yandex-share}"
             ]

volumes:
  yandex-home:
