#!/usr/bin/env -S podman-compose -f

# ./compose.yaml up -d --force-recreate
# ./compose.yaml build --no-cache

version: '2'
services:
  yandex-disk:
#    image: docker.io/kran0/yandex-disk:latest
    image: tt
    restart: always
    volumes:
      - ./share:/opt/share
    environment:
      PASSWORD:     "secret"
      USERNAME:     "owner@yandex.ru"
#      DIR:          "/opt/share"
#      AUTH:         "/tmp/yandex-disk.passwd"
#      EXCLUDE_DIRS: "exclude/dir1,exclude/dir2,path/to/another/exclude/dir"
#      READ_ONLY: true
#      OVERWRITE: true
#      PROXY:        "socks5,my.another.proxy.local,1081"
