#!/usr/bin/env -S podman-compose -f

# How to start sequence:
#
# ./compose-yandex-disk.yaml build --no-cache		# <- build the container
# ./compose-yandex-disk.yaml run --rm yandex-disk token	# <- create auth info volume
#
# # set relative or absolune YANDEX_SHARE path in .env	# <- edit .env
# chcon -R -t svirt_sandbox_file_t ./yandex-share/	# <- chill down selinux
# restorecon -R ./yandex-share/
#
# ./compose-yandex-disk.yaml down			# <- stop service
# ./compose-yandex-disk.yaml up -d --force-recreate	# <- start service

services:
  yandex-disk:
    build:
      context: yandex-disk
      args:
        FEDORA_VERSION: 40
    image: docker.io/kran0/yandex-disk:latest
    restart: always
    environment:
      - HOME=${_CONTAINER_HOME:-/yandex-home}
    volumes:
      - yandex-home:${_CONTAINER_HOME:-/yandex-home}
      - ${YANDEX_SHARE}:${_CONTAINER_SHARE:-/yandex-share}
    command: [ "--no-daemon", "start",
               "--dir=${_CONTAINER_SHARE:-/yandex-share}"
             ]

volumes:
  yandex-home: